site_name: Documentation
site_url: https://github.com/PyPSA/powerplantmatching
repo_url: https://github.com/PyPSA/powerplantmatching
repo_name: PyPSA/powerplantmatching
edit_uri: edit/master/docs/

nav:
  - Home:
    - Home: index.md
    - Usage:
      - Installation: installation.md
      - Getting Started: getting-started.md
      - Basics: basics.md
      - Custom Config: custom-config.md
    - About:
      - Release Notes: release-notes.md
      - Contributors: contributors.md
      - Citing: citing.md
      - License: license.md
    - Support:
      - FAQ: faq.md
      - Support: support.md
      - Troubleshooting: troubleshooting.md
  - Example:
    - Example: examples/example.ipynb
  - API reference:
    - Core modules: api-core.md
    - Data processing modules: api-data.md
    - Utility modules: api-utils.md

# Theme settings
theme:
  name: material
  font:
    text: Overpass
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.tracking  # Anchor tracking
  - navigation.indexes  # Section indexes
  - navigation.path
  - navigation.top # Back to top button
  # - navigation.foot
  - header.autohide
  - content.action.edit
  - content.action.view
  - toc.follow
  - search
  - search.suggest
  - search.highlight
  - search.share
  - announce.dismiss
  - content.code.copy
  - content.code.select

plugins:
  - search
  - autolinks
  - table-reader
  - mkdocs-video
  - mkdocs-jupyter
  # Docstring generation
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: list
            filters:
            - "!logger"
            - "!^_[^_]"
            heading_level: 2
            merge_init_into_class: true
            parameter_headings: false
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            show_if_no_docstring: true
            show_inheritance_diagram: true

markdown_extensions:
  - admonition
  - footnotes
  - abbr
  - attr_list
  - md_in_html
  # Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Toctree with permalinks
  - toc:
      title: On this page
      permalink: true
      toc_depth: 3


extra:
  social:
  - icon: fontawesome/brands/discord
    link: https://discord.com/invite/AnuJBk23FU
  - icon: fontawesome/brands/github
    link: https://github.com/PyPSA/powerplantmatching

  extra:
  homepage: https://pypsa.org

copyright: >-
  &copy Copyright 2015-2025 Powerplantmatching Developers and Contributors
