name: powerplantmatching
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - country_converter
  - geopy
  - ipython
  - matplotlib
  - networkx
  - numpy
  - pandas
  - python=3
  - pyyaml
  - requests
  - scipy
  - seaborn
  - six
  - xlrd
  - openpyxl
  - deprecation
  - pip
  - pip:
    - pycountry
    - entsoe-py>=0.3.1
