version = 1
SPDX-PackageName = "powerplantmatching"
SPDX-PackageSupplyer = "PyPSA"
SPDX-PackageDownloadLocation = "https://github.com/pypsa/powerplantmatching"

[[annotations]]
path = [
    "powerplants.csv",
    "doc/**",
]
SPDX-FileCopyrightText = "The powerplantmatching contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    ".codespell.ignore",
    ".github/**",
    ".gitignore",
    ".readthedocs.yaml",
    ".pre-commit-config.yaml",
]
SPDX-FileCopyrightText = "The powerplantmatching contributors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "powerplantmatching/package_data/*.yaml",
    "powerplantmatching/package_data/*.csv",
    "powerplantmatching/package_data/*.xml",
]
SPDX-FileCopyrightText = "The powerplantmatching contributors"
SPDX-License-Identifier = "CC0-1.0"


[[annotations]]
path = [
    "powerplantmatching/package_data/duke_binaries/*.jar",
]
SPDX-FileCopyrightText = "Lars Marius Garshol <larsga@garshol.priv.no>"
SPDX-License-Identifier = "Apache-2.0"

# TODO powerplantmatching/package_data
# Check all
# Update README.md