blank_issues_enabled: true
contact_links:
- name: Discord Server
  url: https://discord.gg/AnuJBk23FU
  about: To discuss with other PyPSA users, organise projects, share news, and get in touch with the community.

- name: PyPSA Mailing List
  url: https://groups.google.com/forum/#!forum/pypsa
  about: Please ask and answer general usage questions here.

- name: Stackoverflow
  url: https://stackoverflow.com/questions/tagged/pypsa
  about: Please ask and answer code-related questions here.
